language: node_js
node_js:
  - "8"
script: karma start --single-run
before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
# os: osx
# language: node_js
# sudo: required
# addons:
#   chrome: stable
# before_script:
#   - npm install -g karma-cli
# script:
#   - karma start --single-run
# node_js:
#   - "11"